export const shapes = [
  process.env.PUBLIC_URL + '/shapes/back.svg',
  process.env.PUBLIC_URL + '/shapes/comments.svg',
  process.env.PUBLIC_URL + '/shapes/dataLoaded.png',
  process.env.PUBLIC_URL + '/shapes/editCard.svg',
  process.env.PUBLIC_URL + '/shapes/favicon.svg',
  process.env.PUBLIC_URL + '/shapes/info.svg',
  process.env.PUBLIC_URL + '/shapes/likeBorder.svg',
  process.env.PUBLIC_URL + '/shapes/likeFill.svg',
  process.env.PUBLIC_URL + '/shapes/loading.svg',
  process.env.PUBLIC_URL + '/shapes/notFound.svg',
  process.env.PUBLIC_URL + '/shapes/refresh.svg',
  process.env.PUBLIC_URL + '/shapes/scrollDown.svg',
  process.env.PUBLIC_URL + '/shapes/scrollLeft.svg',
  process.env.PUBLIC_URL + '/shapes/scrollRight.svg',
  process.env.PUBLIC_URL + '/shapes/scrollUp.svg',
  process.env.PUBLIC_URL + '/shapes/searchClear.svg',
  process.env.PUBLIC_URL + '/shapes/send.svg',
];